name: Run Tests

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: "0.15.2"

      - name: Run tests
        run: make test
